name: Publish Docker image
on:
  push:
  workflow_dispatch:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - main
          - main-cross
          - main-bookworm
          - main-bookworm-cross
          - main-jammy
          - main-jammy-cross
          - main-focal
          - main-focal-cross
    steps:
      - run: |
          TAG="${{ matrix.tag }}"
          echo "TAG=${TAG/main/${{ github.ref_name }}}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: ${{ env.TAG }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          build-args: |
            base=ghcr.io/anyakichi/dpdk-builder:${{ matrix.tag }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
